apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: aws-example
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: webapp-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: webapp/config
        property: password
    - secretKey: username
      remoteRef:
        key: webapp/config
        property: username
