apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: aws-example
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1 # Specify your AWS region
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: accessKeyID
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secretAccessKey
