apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-keyvault-secret
  namespace: azure-example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-secretstore
    kind: SecretStore
  target:
    name: my-azure-secret
    creationPolicy: Owner
  data:
    - secretKey: webapp-username
      remoteRef:
        key: webapp-username
    - secretKey: webapp-password
      remoteRef:
        key: webapp-password