apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-keyvault-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault-secretstore
    kind: SecretStore
  target:
    name: my-azure-secret
    creationPolicy: Owner
  data:
    - secretKey: my-secret-key
      remoteRef:
        key: my-secret