apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-secretstore
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: "<Your-Azure-Tenant-ID>"
      clientId: "<Your-Azure-Client-ID>"
      clientSecret:
        secretRef:
          name: azure-service-principal-secret
          key: client-secret
      vaultUrl: "https://<Your-Key-Vault-Name>.vault.azure.net/"