apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-secretstore
  namespace: azure-example
spec:
  provider:
    azurekv:
      tenantId: #<set_your_tenant_id>
      vaultUrl: #<add_created_key_vault_url>
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret