apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webapp-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: webapp-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: webapp/config
        property: username
    - secretKey: password
      remoteRef:
        key: webapp/config
        property: password
