apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # Adjust if Vault is outside the cluster
      path: "secret/"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: user-ihk # Ensure this is the correct service account in external-secrets ns
